spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.56.100:3306/hspliving_commodity?useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
#    driver-class-name: com.mysql.jdbc.Driver

# 配置 mybatis-pus
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto # 配置主键信息
      logic-delete-value: 0 # 逻辑已经被删除值(默认为1，这里我们调整为我们自己的 0 )
      logic-not-delete-value: 1 # 逻辑未被删除值(默认值为0，这里我们调整成我们自己的)
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
